
paths:
  ROOT_OUT_PATH: './results/'
  ROOT_CHECKPOINT_PATH: './checkpoint/'
  MODELPATH_NORMFLOW: './checkpoint/barc_normflow_pret/rgbddog_v3_model.pt'
  
optim:
  BATCH_SIZE: 12       # keep 12 (needs to be an even number, as we have a custom data sampler)

data:
  DATASET: 'stanext24'
  VAL_OPT: 'test'  # 'test'